name: Release
on:
  workflow_dispatch:  # Ручной запуск
  push:
    tags: ['v*']     # Автозапуск при тегах (например, v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build  
      - run: echo "Релиз создан!"